spring:
  application:
    name: boardpjt

# profile -> dev, prod
  profiles:
    active: dev
# 디폴트는 노출을 해놓고, dev는 감춰놓을 정보들을 작성
# prod로 가는 애들을 여기에 적어주기
# 공통사항
  datasource: # JPA와 관련있는 것
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true